export type AreaType = 'premium homes' | 'apartments' | 'family homes' | 'growth corridor' | 'older housing' | 'mixed';

export interface KitchenArea {
  name: string;
  slug: string;
  type: AreaType;
  nearby: string[];
  projectStyles: string[];
  quoteRisks: string[];
  preparation: string[];
  intro: string;
}

const areaSeed: Array<Omit<KitchenArea, 'slug'>> = [
  {
    name: 'Mosman',
    type: 'premium homes',
    nearby: ['Neutral Bay', 'Manly', 'Chatswood'],
    projectStyles: ['Full kitchen renovation', 'Premium cabinetry and benchtop upgrade', 'Kitchen and living-area refresh'],
    quoteRisks: ['High finish expectations', 'Detailed joinery scope', 'Access and parking planning'],
    preparation: ['Photos of existing cabinetry and services', 'Finish inspiration', 'Any designer plans or appliance schedule'],
    intro: 'Mosman kitchen projects often involve premium finishes, careful site access and a strong expectation that scope, allowances and selections are clear before site measure.',
  },
  {
    name: 'Vaucluse',
    type: 'premium homes',
    nearby: ['Rose Bay', 'Double Bay', 'Bellevue Hill'],
    projectStyles: ['Architectural kitchen renovation', 'Stone-alternative benchtop review', 'Large family kitchen upgrade'],
    quoteRisks: ['Premium surface selections', 'Appliance allowance clarity', 'Delivery and access constraints'],
    preparation: ['Room measurements', 'Photos of all walls', 'Preferred appliance brands or allowance level'],
    intro: 'Vaucluse renovations commonly need strong selection clarity, premium finish review and careful allowance wording before quotes can be compared properly.',
  },
  {
    name: 'Double Bay',
    type: 'apartments',
    nearby: ['Bellevue Hill', 'Woollahra', 'Rose Bay'],
    projectStyles: ['Apartment kitchen renovation', 'Compact premium kitchen', 'Quote review before strata submission'],
    quoteRisks: ['Strata approvals', 'Lift booking and work-hour limits', 'Service relocation review'],
    preparation: ['Strata requirements', 'Lift and parking notes', 'Photos of plumbing and electrical locations'],
    intro: 'Double Bay projects often combine apartment access constraints with premium finishes, so quote confidence depends on clear approvals, access and service assumptions.',
  },
  {
    name: 'Bellevue Hill',
    type: 'premium homes',
    nearby: ['Double Bay', 'Woollahra', 'Vaucluse'],
    projectStyles: ['Luxury kitchen renovation', 'Cabinetry and island redesign', 'Benchtop and splashback upgrade'],
    quoteRisks: ['Custom joinery detail', 'Premium hardware selections', 'Existing wall and service conditions'],
    preparation: ['Kitchen photos', 'Plans if available', 'Preferred finish tier and benchtop direction'],
    intro: 'Bellevue Hill kitchens can vary widely in scope, from premium refreshes to complex renovations with custom joinery and higher selection detail.',
  },
  {
    name: 'Woollahra',
    type: 'older housing',
    nearby: ['Double Bay', 'Bellevue Hill', 'Rose Bay'],
    projectStyles: ['Terrace kitchen renovation', 'Period-home kitchen refresh', 'Compact kitchen quote review'],
    quoteRisks: ['Older-property conditions', 'Access limitations', 'Heritage or strata review'],
    preparation: ['Photos of walls, floors and ceilings', 'Property age notes', 'Any approval or heritage information'],
    intro: 'Woollahra kitchens often need extra care around older buildings, access and existing services before a planning estimate can tighten.',
  },
  {
    name: 'Rose Bay',
    type: 'mixed',
    nearby: ['Vaucluse', 'Double Bay', 'Bellevue Hill'],
    projectStyles: ['Apartment kitchen update', 'Family kitchen renovation', 'Benchtop and cabinetry refresh'],
    quoteRisks: ['Apartment access', 'Finish allowance clarity', 'Licensed trade scope'],
    preparation: ['Photos and room dimensions', 'Current quote if available', 'Service relocation notes'],
    intro: 'Rose Bay has a mix of homes and apartments, so the estimate should identify access, strata, service and finish assumptions early.',
  },
  {
    name: 'Neutral Bay',
    type: 'apartments',
    nearby: ['Mosman', 'Manly', 'Chatswood'],
    projectStyles: ['Apartment kitchen renovation', 'Cabinetry refresh', 'Quote review for strata-ready scope'],
    quoteRisks: ['Lift and parking access', 'Class 2 screening', 'Waste removal scope'],
    preparation: ['Building access notes', 'Floorplan', 'Photos of service points'],
    intro: 'Neutral Bay apartment projects benefit from early review of access, strata requirements and service assumptions before comparing quote totals.',
  },
  {
    name: 'Manly',
    type: 'mixed',
    nearby: ['Mosman', 'Neutral Bay', 'Chatswood'],
    projectStyles: ['Beachside apartment kitchen', 'Family home kitchen renovation', 'Durable finish upgrade'],
    quoteRisks: ['Apartment access', 'Moisture-resistant material choices', 'Parking and delivery planning'],
    preparation: ['Photos, plans and access notes', 'Finish durability preferences', 'Existing quote documents'],
    intro: 'Manly kitchen renovations can involve apartment rules, coastal durability preferences and careful delivery planning.',
  },
  {
    name: 'Wahroonga',
    type: 'family homes',
    nearby: ['Pymble', 'Killara', 'Chatswood'],
    projectStyles: ['Large family kitchen renovation', 'Butler pantry addition', 'Kitchen and laundry scope review'],
    quoteRisks: ['Multiple zones', 'Structural or service changes', 'Premium cabinetry quantity'],
    preparation: ['Zone list', 'Measurements', 'Appliance intentions and finish direction'],
    intro: 'Wahroonga projects often involve larger family kitchens where cabinetry quantity, appliance planning and adjacent zones shape the estimate.',
  },
  {
    name: 'Pymble',
    type: 'family homes',
    nearby: ['Wahroonga', 'Killara', 'Chatswood'],
    projectStyles: ['Family kitchen upgrade', 'Cabinetry and benchtop refresh', 'Open-plan kitchen renovation'],
    quoteRisks: ['Cabinet run length', 'Flooring touch-up boundaries', 'Electrical and lighting scope'],
    preparation: ['Photos of adjoining areas', 'Measurements', 'Lighting and appliance notes'],
    intro: 'Pymble kitchen quotes are clearer when the cabinetry run, appliance allowance and adjoining finish boundaries are separated early.',
  },
  {
    name: 'Killara',
    type: 'family homes',
    nearby: ['Pymble', 'Wahroonga', 'Chatswood'],
    projectStyles: ['Premium family kitchen', 'Island and storage upgrade', 'Kitchen renovation estimate'],
    quoteRisks: ['Joinery detail', 'Benchtop cut-outs and joins', 'Service relocation'],
    preparation: ['Floorplan if available', 'Photos of services', 'Preferred benchtop alternatives'],
    intro: 'Killara kitchen projects often need clear joinery, benchtop and service assumptions before the budget range can be trusted.',
  },
  {
    name: 'Balmain',
    type: 'older housing',
    nearby: ['Drummoyne', 'Lane Cove', 'Hunters Hill'],
    projectStyles: ['Terrace kitchen renovation', 'Compact kitchen redesign', 'Older-home quote review'],
    quoteRisks: ['Older walls and floors', 'Restricted access', 'Asbestos or heritage review'],
    preparation: ['Property age notes', 'Photos of floors and walls', 'Access and parking details'],
    intro: 'Balmain kitchens often sit in older homes where access, existing conditions and make-good scope need early review.',
  },
  {
    name: 'Drummoyne',
    type: 'mixed',
    nearby: ['Balmain', 'Hunters Hill', 'Ryde'],
    projectStyles: ['Family home kitchen', 'Apartment kitchen review', 'Cabinetry refresh'],
    quoteRisks: ['Access differences', 'Service relocation', 'Allowance clarity'],
    preparation: ['Photos, measurements and quote files', 'Property type', 'Preferred timing'],
    intro: 'Drummoyne projects vary between houses and apartments, so quote clarity starts with property type, access and trade assumptions.',
  },
  {
    name: 'Coogee',
    type: 'apartments',
    nearby: ['Randwick', 'Bondi', 'Rose Bay'],
    projectStyles: ['Apartment kitchen renovation', 'Benchtop replacement', 'Quote review before approval'],
    quoteRisks: ['Strata access', 'Lift and parking', 'Material durability'],
    preparation: ['Strata rules', 'Photos of service points', 'Benchtop and splashback notes'],
    intro: 'Coogee apartment kitchens need access, strata and material choices captured early so the estimate does not hide practical constraints.',
  },
  {
    name: 'Randwick',
    type: 'mixed',
    nearby: ['Coogee', 'Bondi', 'Rose Bay'],
    projectStyles: ['Apartment kitchen', 'Family home renovation', 'Cabinetry and surface refresh'],
    quoteRisks: ['Apartment approvals', 'Older-property conditions', 'Service movement'],
    preparation: ['Photos and plans', 'Age of property if known', 'Current quote or scope notes'],
    intro: 'Randwick kitchen estimates should account for apartments, older homes and service relocation uncertainty before review.',
  },
  {
    name: 'Bondi',
    type: 'apartments',
    nearby: ['Coogee', 'Randwick', 'Rose Bay'],
    projectStyles: ['Compact apartment kitchen', 'Durable beachside finishes', 'Quote review'],
    quoteRisks: ['Strata and access', 'Moisture and material suitability', 'Waste and delivery planning'],
    preparation: ['Access notes', 'Photos', 'Finish direction and quote files'],
    intro: 'Bondi kitchen projects often require careful apartment access planning and durable finish choices alongside clear allowance wording.',
  },
  {
    name: 'Chatswood',
    type: 'apartments',
    nearby: ['Lane Cove', 'Ryde', 'Pymble'],
    projectStyles: ['Apartment kitchen renovation', 'Family unit refresh', 'Quote review'],
    quoteRisks: ['Class 2 review', 'Lift bookings', 'Service and appliance assumptions'],
    preparation: ['Building requirements', 'Floorplan', 'Appliance allowance notes'],
    intro: 'Chatswood kitchen projects commonly involve apartments, so strata, lift access and class 2 screening should be considered early.',
  },
  {
    name: 'Lane Cove',
    type: 'mixed',
    nearby: ['Chatswood', 'Ryde', 'Hunters Hill'],
    projectStyles: ['Townhouse kitchen', 'Apartment kitchen', 'Family kitchen refresh'],
    quoteRisks: ['Parking and delivery', 'Strata or townhouse approvals', 'Finish allowance clarity'],
    preparation: ['Property type', 'Access notes', 'Photos and rough dimensions'],
    intro: 'Lane Cove projects benefit from early separation of access, property type and selection assumptions.',
  },
  {
    name: 'Hunters Hill',
    type: 'premium homes',
    nearby: ['Lane Cove', 'Drummoyne', 'Ryde'],
    projectStyles: ['Premium home kitchen', 'Older-home renovation', 'Kitchen and pantry scope'],
    quoteRisks: ['Older-property review', 'Custom joinery', 'Premium finish selections'],
    preparation: ['Plans or sketches', 'Property age notes', 'Preferred finish tier'],
    intro: 'Hunters Hill kitchen quotes often need custom joinery, older-home and premium finish assumptions documented before site measure.',
  },
  {
    name: 'Parramatta',
    type: 'mixed',
    nearby: ['Auburn', 'Ryde', 'Strathfield'],
    projectStyles: ['Apartment kitchen', 'Family home renovation', 'Investment property refresh'],
    quoteRisks: ['Mixed building types', 'Budget and allowance clarity', 'Access conditions'],
    preparation: ['Property type', 'Photos and measurements', 'Budget band and timing'],
    intro: 'Parramatta kitchen projects range from apartments to family homes, so the estimate should clearly separate project type and allowance choices.',
  },
  {
    name: 'Bankstown',
    type: 'family homes',
    nearby: ['Auburn', 'Fairfield', 'Cabramatta'],
    projectStyles: ['Family kitchen renovation', 'Rental or investment refresh', 'Benchtop replacement'],
    quoteRisks: ['Budget band alignment', 'Service assumptions', 'Demolition and waste scope'],
    preparation: ['Photos', 'Measurements', 'List of inclusions and exclusions to check'],
    intro: 'Bankstown kitchen estimates are stronger when scope, trade work and allowance levels are clear from the start.',
  },
  {
    name: 'Strathfield',
    type: 'family homes',
    nearby: ['Burwood', 'Auburn', 'Parramatta'],
    projectStyles: ['Family home kitchen', 'Apartment kitchen', 'Premium refresh'],
    quoteRisks: ['Cabinetry quantity', 'Service relocation', 'Access and parking'],
    preparation: ['Kitchen dimensions', 'Photos', 'Appliance and finish preferences'],
    intro: 'Strathfield kitchens often need clarity around cabinetry quantity, services and finish direction before comparing quote totals.',
  },
  {
    name: 'Burwood',
    type: 'apartments',
    nearby: ['Strathfield', 'Auburn', 'Ryde'],
    projectStyles: ['Apartment kitchen', 'Compact kitchen renovation', 'Quote review'],
    quoteRisks: ['Apartment access', 'Strata approval', 'Service relocation'],
    preparation: ['Strata notes', 'Floorplan if available', 'Photos of existing kitchen'],
    intro: 'Burwood kitchen projects often involve apartments and mixed access conditions, making strata and service assumptions important.',
  },
  {
    name: 'Ryde',
    type: 'mixed',
    nearby: ['Lane Cove', 'Chatswood', 'Parramatta'],
    projectStyles: ['Family home kitchen', 'Apartment kitchen', 'Cabinetry refresh'],
    quoteRisks: ['Property type variation', 'Access notes', 'Service and appliance assumptions'],
    preparation: ['Property type', 'Photos, plans or sketches', 'Current quote if available'],
    intro: 'Ryde has varied kitchen project types, so early estimate confidence depends on clear property and scope details.',
  },
  {
    name: 'Epping',
    type: 'family homes',
    nearby: ['Ryde', 'Castle Hill', 'Parramatta'],
    projectStyles: ['Family kitchen renovation', 'Townhouse kitchen', 'Kitchen and pantry scope'],
    quoteRisks: ['Cabinetry run length', 'Electrical and lighting scope', 'Access and parking'],
    preparation: ['Measurements', 'Photos', 'Lighting and appliance notes'],
    intro: 'Epping kitchen quotes are clearer when measurements, finish tier and trade scope are captured before site review.',
  },
  {
    name: 'Castle Hill',
    type: 'family homes',
    nearby: ['Baulkham Hills', 'Epping', 'Parramatta'],
    projectStyles: ['Large family kitchen', 'Kitchen and butler pantry', 'Full renovation estimate'],
    quoteRisks: ['Multiple zones', 'Appliance allowance', 'Structural or service changes'],
    preparation: ['Zone list', 'Appliance intentions', 'Photos and plans'],
    intro: 'Castle Hill projects often involve larger kitchens and adjacent spaces, so zone-by-zone scope clarity is important.',
  },
  {
    name: 'Baulkham Hills',
    type: 'family homes',
    nearby: ['Castle Hill', 'Epping', 'Parramatta'],
    projectStyles: ['Family kitchen renovation', 'Cabinetry and benchtop refresh', 'Kitchen/laundry planning'],
    quoteRisks: ['Scope boundaries', 'Finish tiers', 'Trade relocation'],
    preparation: ['Project type', 'Photos', 'Finish and appliance preferences'],
    intro: 'Baulkham Hills kitchen estimates should separate refresh work from full renovation scope and trade changes.',
  },
  {
    name: 'Liverpool',
    type: 'growth corridor',
    nearby: ['Edmondson Park', 'Fairfield', 'Bankstown'],
    projectStyles: ['Newer-home kitchen upgrade', 'Investment property refresh', 'Family kitchen renovation'],
    quoteRisks: ['Budget alignment', 'Appliance allowance', 'Delivery and timing'],
    preparation: ['Budget band', 'Photos', 'Appliance allowance direction'],
    intro: 'Liverpool kitchen projects often need practical budget alignment and clear allowance choices before site measure.',
  },
  {
    name: 'Edmondson Park',
    type: 'growth corridor',
    nearby: ['Liverpool', 'Leppington', 'Campbelltown'],
    projectStyles: ['Newer-home kitchen upgrade', 'Builder-grade refresh', 'Storage improvement'],
    quoteRisks: ['Existing builder finishes', 'Upgrade boundaries', 'Appliance and hardware choices'],
    preparation: ['Photos of existing finishes', 'Upgrade wishlist', 'Appliance notes'],
    intro: 'Edmondson Park projects often focus on upgrading newer-home finishes, storage and benchtop direction.',
  },
  {
    name: 'Leppington',
    type: 'growth corridor',
    nearby: ['Edmondson Park', 'Camden', 'Campbelltown'],
    projectStyles: ['New-home kitchen upgrade', 'Family kitchen planning', 'Benchtop and cabinetry refresh'],
    quoteRisks: ['Upgrade scope boundaries', 'Timing and access', 'Allowance level'],
    preparation: ['Photos', 'Builder plans if available', 'Finish direction'],
    intro: 'Leppington kitchen planning often centres on newer-home upgrades where scope boundaries and selection levels should be clear.',
  },
  {
    name: 'Camden',
    type: 'family homes',
    nearby: ['Leppington', 'Campbelltown', 'Liverpool'],
    projectStyles: ['Family kitchen renovation', 'Country-style kitchen', 'Large kitchen and pantry scope'],
    quoteRisks: ['Cabinet quantity', 'Delivery planning', 'Finish and hardware selections'],
    preparation: ['Room dimensions', 'Photos', 'Style and finish preferences'],
    intro: 'Camden kitchen projects can involve larger family spaces, where cabinetry quantity and finish direction drive estimate confidence.',
  },
  {
    name: 'Campbelltown',
    type: 'family homes',
    nearby: ['Camden', 'Leppington', 'Liverpool'],
    projectStyles: ['Family kitchen renovation', 'Budget-conscious refresh', 'Benchtop replacement'],
    quoteRisks: ['Budget band', 'Demolition scope', 'Service assumptions'],
    preparation: ['Photos and dimensions', 'Budget band', 'Scope wishlist'],
    intro: 'Campbelltown kitchen estimates should make budget band, demolition and trade assumptions clear before comparing options.',
  },
  {
    name: 'Miranda',
    type: 'mixed',
    nearby: ['Randwick', 'Coogee', 'Bondi'],
    projectStyles: ['Apartment kitchen', 'Family home kitchen', 'Benchtop refresh'],
    quoteRisks: ['Mixed property types', 'Access and parking', 'Service assumptions'],
    preparation: ['Property type', 'Photos', 'Existing quote if available'],
    intro: 'Miranda projects can vary from apartments to houses, so access, service and finish assumptions should be captured early.',
  },
  {
    name: 'Blacktown',
    type: 'family homes',
    nearby: ['Parramatta', 'Auburn', 'Fairfield'],
    projectStyles: ['Family kitchen renovation', 'Investment refresh', 'Cabinetry and benchtop upgrade'],
    quoteRisks: ['Budget and allowance clarity', 'Demolition and waste', 'Licensed trade scope'],
    preparation: ['Photos', 'Measurements', 'List of inclusions to check'],
    intro: 'Blacktown kitchen quote clarity depends on separating inclusions, allowances, trade scope and exclusions early.',
  },
  {
    name: 'Auburn',
    type: 'mixed',
    nearby: ['Parramatta', 'Strathfield', 'Bankstown'],
    projectStyles: ['Apartment kitchen', 'Family kitchen', 'Investment property refresh'],
    quoteRisks: ['Property type', 'Service movement', 'Access and parking'],
    preparation: ['Property details', 'Photos', 'Current quote or checklist'],
    intro: 'Auburn kitchen projects benefit from practical scope intake that accounts for property type, service assumptions and access.',
  },
  {
    name: 'Fairfield',
    type: 'family homes',
    nearby: ['Cabramatta', 'Bankstown', 'Liverpool'],
    projectStyles: ['Family kitchen renovation', 'Cabinetry refresh', 'Benchtop replacement'],
    quoteRisks: ['Budget band', 'Scope boundaries', 'Trade assumptions'],
    preparation: ['Photos', 'Measurements', 'Preferred finish tier'],
    intro: 'Fairfield kitchen estimates should keep budget, finish and trade assumptions clear before a site visit.',
  },
  {
    name: 'Cabramatta',
    type: 'family homes',
    nearby: ['Fairfield', 'Bankstown', 'Liverpool'],
    projectStyles: ['Family kitchen renovation', 'Practical refresh', 'Quote comparison'],
    quoteRisks: ['Scope inclusions', 'Appliance allowance', 'Demolition and waste'],
    preparation: ['Photos', 'Appliance preferences', 'Current quote if comparing'],
    intro: 'Cabramatta kitchen quote review is strongest when inclusions, appliance allowances and demolition scope are clearly separated.',
  },
];

export const kitchenAreas: KitchenArea[] = areaSeed.map((area) => ({
  ...area,
  slug: area.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
}));

export const priorityFooterAreas = [
  'Mosman',
  'Vaucluse',
  'Double Bay',
  'Bellevue Hill',
  'Woollahra',
  'Rose Bay',
  'Neutral Bay',
  'Manly',
  'Chatswood',
  'Wahroonga',
  'Pymble',
  'Killara',
  'Balmain',
  'Coogee',
  'Randwick',
];

export function getKitchenArea(slug: string) {
  return kitchenAreas.find((area) => area.slug === slug) || null;
}

export function getAreaHref(areaName: string) {
  const area = kitchenAreas.find((item) => item.name === areaName);
  return area ? `/areas/${area.slug}` : '/areas';
}
